MVC_DataBase/MVC_DataBase/Models/ErrorViewModel.cs
using System;

namespace MVC_DataBase.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

MVC_DataBase/MVC_DataBase/Controllers/EmployeeController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.ModelBinding;
using MVC_DataBase.DATA;
using System.Collections.Generic;

namespace MVC_DataBase.Controllers
{
    public class EmployeeController : Controller
    {
        private readonly IEmployeeRepository _employeeRepository;
        private IEnumerable<Employee> employees;

        public EmployeeController(IEmployeeRepository employeeRepository)
        {
            _employeeRepository = employeeRepository;
        }

        public IActionResult Details(int id)
        {
            Employee employee = _employeeRepository.GetById(id);
            return View(employee);
        }

        public IActionResult Index()
        {
            employees = _employeeRepository.GetAll();
            return View(employees);
        }

        [HttpGet]
        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(Employee employee)
        {
            if (ModelState.IsValid)
            {
                _employeeRepository.Add(employee);
                return RedirectToAction("Index");
            }
            else 
            {
                return View(employee);
            }
            
        }
        
        [HttpGet]
        public IActionResult Edit(int id)
        {
            Employee employee = _employeeRepository.GetById(id);
            return View(employee);
        }

        [HttpPost]
        public IActionResult Edit(Employee employee)
        {
            _employeeRepository.Update(employee);
            return RedirectToAction("Index");
        }
        [HttpGet]
        public IActionResult Delete(int id)
        {
            Employee employee = _employeeRepository.GetById(id);
            return View(employee);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Delete(Employee employee)
        {
            _employeeRepository.Delete(employee);
            return RedirectToAction("Index");
        }
    }
}

MVC_DataBase/MVC_DataBase/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using MVC_DataBase.Models;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;

namespace MVC_DataBase.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

MVC_DataBase/MVC_DataBase/Views/Employee/Create.cshtml
@model MVC_DataBase.DATA.Employee

@{
    ViewData["Title"] = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Create</h1>

<h4>Employee</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="FirstName" class="control-label"></label>
                <input asp-for="FirstName" class="form-control" />
                <span asp-validation-for="FirstName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="LastName" class="control-label"></label>
                <input asp-for="LastName" class="form-control" />
                <span asp-validation-for="LastName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Department" class="control-label"></label>
                <input asp-for="Department" class="form-control" />
                <span asp-validation-for="Department" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Basic" class="control-label"></label>
                <input asp-for="Basic" class="form-control" />
                <span asp-validation-for="Basic" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Email" class="control-label"></label>
                <input asp-for="Email" class="form-control" />
                <span asp-validation-for="Email" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="PhoneNumber" class="control-label"></label>
                <input asp-for="PhoneNumber" class="form-control" />
                <span asp-validation-for="PhoneNumber" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="WebUrl" class="control-label"></label>
                <input asp-for="WebUrl" class="form-control" />
                <span asp-validation-for="WebUrl" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="DA" class="control-label"></label>
                <input asp-for="DA" class="form-control" />
                <span asp-validation-for="DA" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="HRA" class="control-label"></label>
                <input asp-for="HRA" class="form-control" />
                <span asp-validation-for="HRA" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="NetSalary" class="control-label"></label>
                <input asp-for="NetSalary" class="form-control" />
                <span asp-validation-for="NetSalary" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

MVC_DataBase/MVC_DataBase/Views/Employee/Delete.cshtml
@model MVC_DataBase.DATA.Employee

@{
    ViewData["Title"] = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Employee</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Id)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Id)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.FirstName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.FirstName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.LastName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.LastName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Department)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Department)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Basic)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Basic)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Email)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Email)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.PhoneNumber)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.PhoneNumber)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.WebUrl)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.WebUrl)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.DA)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.DA)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.HRA)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.HRA)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.NetSalary)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.NetSalary)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

MVC_DataBase/MVC_DataBase/Views/Employee/Details.cshtml
@model MVC_DataBase.DATA.Employee

@{
    ViewData["Title"] = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Details</h1>

<div>
    <h4>Employee</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Id)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Id)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.FirstName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.FirstName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.LastName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.LastName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Department)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Department)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Basic)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Basic)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Email)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Email)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.PhoneNumber)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.PhoneNumber)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.WebUrl)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.WebUrl)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.DA)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.DA)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.HRA)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.HRA)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.NetSalary)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.NetSalary)
        </dd>
    </dl>
</div>
<div>
    @Html.ActionLink("Edit", "Edit", new { id = Model.Id }) |
    <a asp-action="Index">Back to List</a>
</div>

MVC_DataBase/MVC_DataBase/Views/Employee/Edit.cshtml
@model MVC_DataBase.DATA.Employee

@{
    ViewData["Title"] = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Edit</h1>

<h4>Employee</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group"; id="divCheckbox" style="display: none;">
                <label asp-for="Id" class="control-label"></label>
                <input asp-for="Id" class="form-control" />
                <span asp-validation-for="Id" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="FirstName" class="control-label"></label>
                <input asp-for="FirstName" class="form-control" />
                <span asp-validation-for="FirstName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="LastName" class="control-label"></label>
                <input asp-for="LastName" class="form-control" />
                <span asp-validation-for="LastName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Department" class="control-label"></label>
                <input asp-for="Department" class="form-control" />
                <span asp-validation-for="Department" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Basic" class="control-label"></label>
                <input asp-for="Basic" class="form-control" />
                <span asp-validation-for="Basic" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Email" class="control-label"></label>
                <input asp-for="Email" class="form-control" />
                <span asp-validation-for="Email" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="PhoneNumber" class="control-label"></label>
                <input asp-for="PhoneNumber" class="form-control" />
                <span asp-validation-for="PhoneNumber" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="WebUrl" class="control-label"></label>
                <input asp-for="WebUrl" class="form-control" />
                <span asp-validation-for="WebUrl" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="DA" class="control-label"></label>
                <input asp-for="DA" class="form-control" />
                <span asp-validation-for="DA" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="HRA" class="control-label"></label>
                <input asp-for="HRA" class="form-control" />
                <span asp-validation-for="HRA" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="NetSalary" class="control-label"></label>
                <input asp-for="NetSalary" class="form-control" />
                <span asp-validation-for="NetSalary" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>
@*
@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}*@

MVC_DataBase/MVC_DataBase/Views/Employee/Index.cshtml
@using MVC_DataBase.DATA
@model IEnumerable<Employee>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>List of Employee</h2>
    
    <p>
        @Html.ActionLink("Create New", "Create")
    </p>
    <table class="table">
        <tr>
            <th>@Html.DisplayNameFor(model => model.FirstName)
            </th>
            <th>@Html.DisplayNameFor(model => model.LastName)
            </th>
            <th>@Html.DisplayNameFor(model => model.Department)
            </th>
            <th></th>
        </tr>
        @if (Model != null)
       {
        @foreach (var employee in Model) 
           {
            <tr>
            <td>@Html.DisplayFor(modelItem => employee.FirstName)
            </td>
            <td>@Html.DisplayFor(modelItem => employee.LastName)
            </td>
            <td>@Html.DisplayFor(modelItem => employee.Department)
            </td>
            <td>@Html.ActionLink("Edit", "Edit", new { id=employee.Id }) |
                @Html.ActionLink("Details", "Details", new { id=employee.Id }) |
                @Html.ActionLink("Delete", "Delete", new { id=employee.Id })
            </td>
            </tr>
           }
       }
       else
       {
           <tr>
           <td><h2>NO DETA</h2></td>
           <td></td>
           <td></td>
           <td></td>
           </tr>
       }
        
    </table>

MVC_DataBase/MVC_DataBase/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

MVC_DataBase/MVC_DataBase/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - MVC_DataBase</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">MVC_DataBase</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                         <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Employee" asp-action="Index">Employee</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - MVC_DataBase - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>